### PR TITLE
More Porting, Fixes, Additions and Updating to r112

### PR DESCRIPTION
**Pull request by michaelsakharov**
Some Raycast code including Skeletons and SkinnedMesh code, and a few Methods for InstancedMesh.
Also updated Json Newtonsoft as visual studio for some reason was complaining and not downloading the previous version.

### CODE REVIEW

**Comment by michaelsakharov** [comment]
Added RectAreaLightHelper, There are some rendering artifacts with RectAreaLights but it seems to work.

**Comment by michaelsakharov** [comment]
Disabled LTC for RectAreaLight, makes it look kinda bad since it removes all Specular results from the light, but it works atleast.

**Comment by michaelsakharov** [comment]
Fully updated everything in the project to r111.

**Comment by michaelsakharov** [comment]
Fully updated everything in the project to r112.

**Comment by michaelsakharov** [comment]
Added the Sky Object from the Threejs Examples
Fixed a Memory leak with RectAreaLights

**Review by hjoykim — APPROVED** [review]

**Review by hjoykim — APPROVED** [review]

**Pull request merged**
